
spring:
  datasource:
    url: jdbc:mariadb://localhost:3388/user_center
    hikari:
      username: root
      password: root123
      driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8082